baseURL = "https://b08.dev"
languageCode = "en"
title = "B08"

[markup.goldmark.extensions]
  table = true

[params]
  description = "Jacob Meilutat — Backend & App Developer, Berlin"
  author = "Jacob Meilutat"

[menu]
  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
