baseURL = "https://b08.io"
languageCode = "en"
title = "B08"

[markup.goldmark.extensions]
  table = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "Jacob Meilutat — Backend & App Developer, Berlin"
  author = "Jacob Meilutat"
  email = "jacob@b08.io"
  github = "https://github.com/unJaco"
  linkedin = "https://www.linkedin.com/in/jacob-meilutat/"

[menu]
  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
